version: "3.7"
services:
 voting-app:
  build: ./example-voting-app/vote
  image: voting-app
  ports: 
   - 5000:80
  container_name: myvoting
  networks:
   - net1


 redis:
  image: redis
  container_name: redis
  networks:
   - net1
   - net3
 worker:
  image: worker
  build: ./example-voting-app/worker
  volumes:
   - worker_volu:/var/lib/postgresql/data
  networks:
   - net3

 db:
  image: postgres
  container_name: db
  environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
  networks:
   - net3
   - net2

 result-app:
  image: result
  build: ./example-voting-app/result
  ports: 
   - 5001:80
  networks:
   - net2

volumes:
 worker_volu:
  external: true

networks:
 net1:
  external: true
 net2:
  external: true
 net3:
  external: true



