version: "3.7"
services:
 web:
  image: fundamentalsofdocker/ch08-web:1.0
  ports: 
   - 3000
 db:
  image: fundamentalsofdocker/ch08-db:1.0
  volumes:
   - pets-data:/var/lib/postgresql/data
  container_name: db

volumes:
 pets-data:

