version: "3.7"
services:
 web:
  image: nginx
  volumes:
   - nginxweb:/usr/share/nginx/html
   - nginxconf:/etc/nginx/conf.d/
  ports:
   - 80:80 
  
volumes:
 nginxweb:
  external: true
 nginxconf: 
  external: true
